name: DEV Environment Deployment 

on:
  push:
    branches: 
      - dev
      - development

env:
  # Docker Credentials
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # CI Registry
  CI_REGISTRY: ghcr.io/${{ github.repository }}
  CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

  # Application Info
  APPLICATION_NAME: yui
  APPLICATION_NAMESPACE: yui-dev
  APPLICATION_VERSION: 1.0.0-dev
  APPLICATION_PROFILE: 'dev'
  

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run:  |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $CI_REGISTRY
      
      - name: Build Docker Image
        run: |
          docker build -t $CI_REGISTRY_IMAGE:$APPLICATION_VERSION .

      - name: Push Docker Image
        run: |
          docker push $CI_REGISTRY_IMAGE:$APPLICATION_VERSION
